dist: bionic
language: node_js
addons:
  apt:
    packages:
      - 'python3'
      - 'python3-pip'
      - 'python3-setuptools'
node_js:
  - lts/*
python:
  - '3.8'
install:
  - pip3 install awscli
  - npm install --only=prod
script:
  - npm run build
  - aws configure set aws_access_key_id $S3_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $S3_SECRET_ACCESS_KEY
  - >
    aws s3 sync ./dist s3://$S3_BUCKET
    --exclude="*"
    --include="**/*.js.br"
    --content-encoding br
    --content-type="application/javascript"
  - >
    aws s3 sync ./dist s3://$S3_BUCKET
    --exclude="*"
    --include="*.html.br"
    --content-encoding br
    --content-type="text/html"
  - aws s3 sync ./dist s3://$S3_BUCKET --exclude="**/*.js.br" --exclude="*.html.br"
  - aws s3 sync ./dist s3://$S3_BUCKET --delete
  - >
    aws cloudfront create-invalidation
    --distribution-id $AWS_DISTRIBUTION_ID
    --paths "/index.html" "/index.html.br"
