export const list = [
  "01 The Trail.mp3",
  "02 Geralt of Rivia.mp3",
  "03 Eredin, King of the Hunt.mp3",
  "04 Wake Up, Ciri.mp3",
  "05 Aen Seidhe.mp3",
  "06 Commanding the Fury.mp3",
  "07 Emhyr var Emreis.mp3",
  "08 Spikeroog.mp3",
  "09 King Bran's Final Voyage.mp3",
  "10 Silver for Monsters....mp3",
  "11 Whispers of Oxenfurt.mp3",
  "12 The Nightingale.mp3",
  "13 City of Intrigues.mp3",
  "14 The Hunter's Path.mp3",
  "15 Widow-maker.mp3",
  "16 Kaer Morhen.mp3",
  "17 Eyes of the Wolf.mp3",
  "18 Witch Hunters.mp3",
  "19 ...Steel for Humans.mp3",
  "20 Fate Calls.mp3",
  "21 The Vagabond.mp3",
  "22 Cloak and Dagger.mp3",
  "23 Forged in Fire.mp3",
  "24 Yes, I Do....mp3",
  "25 Welcome, Imlerith.mp3",
  "26 Drink Up, There_s More!.mp3",
  "27 After the Storm.mp3",
  "28 Blood on the Cobblestones.mp3",
  "29 Farewell, Old Friend.mp3",
  "30 The Song of the Sword–Dancer.mp3",
  "31 The Hunt is Coming.mp3",
  "32 The Fields of Ard Skellig.mp3",
  "33 Ladies of the Woods.mp3",
  "34 Merchants of Novigrad.mp3",
  "35 Hunt Or Be Hunted.mp3",
]